### ISSUE TITLE
AFNetworking receive GZIP json

### ISSUE THREAD

**Issue by xumeng** [AFNetworking/AFgzipRequestSerializer#3]
Does AFN can receive the json that use gzip compress?

**Comment by matths** [comment]
I took the AFgzipRequestSerializer as an example of a RequestSerializer wrapping another one.
Also it's not needed for gunzip of responses, it would be nice, to have an example for the responseSerializer as well.
My use case is JWT (basically some String wrapping the JSON payload). See https://github.com/AFNetworking/AFNetworking/issues/2829
